### ISSUE TITLE
script tag in fenced code breaks

### ISSUE THREAD

**Issue by m4b** [PolymerElements/marked-element#10]
I've noticed that a script tag in a code fence seems to break the markdown processor, e.g.:

``````
        <marked-element>
          <script type="text/markdown">
           ````html
            <html>
              <head>
                <base href="http://element-party.xyz/">
                <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
                <link rel="import" href="all-elements.html">
              </head>
              <body>
                <rename-me></rename-me>
                <dom-module id="rename-me">
                  <style>
                  </style>
                  <template>
                    <paper-button>
                      Touch Me
                    </paper-button>
                  </template>
                  <script>
                   Polymer ({
                     is: 'rename-me'                     
                   });
                  </ script>
                </dom-module>
              </body>
            </html>
           ````
          </script>
        </marked-element>
``````

yields the first four ` marks and the language tag, and nothing else (if the gfm language tag and the extra ` are not used, and only three `'s, the issue still persists).  However, if the closing `</script>` tag is modified to be `</ script>`, it is processed as expected, e.g.:

``` html
<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></ script>
```

I'm not sure if this is an issue with the element wrapper or with the marked library itself (my guess is the second).

**Comment by devinivy** [comment]
Verified– we're having the same issue.

**Comment by notwaldorf** [comment]
I think you need to escape the brackets in the `</script>` bit (`&lt;/script&lg;`), or else it will literally close the markdown script and stop parsing. I don't think there's anything we can do on the element side to make this less painful

**Comment by notwaldorf** [comment]
Re-opening. @cdata had the idea to also use `<noscript>` tags instead of `<script>` in this element as an alternate way to pass the script, which would fix this issue.

Any interest from the community to help with this PR? :)

**Comment by stramel** [comment]
@notwaldorf I believe this is possible at this point in time since it only looks for `[type^="text/markdown"]`.

Personal testing with `<noscript type="text/markdown">...</noscript>` appears to work.

Alternatively, using `src` property being added in #51 will work as well.
