### ISSUE TITLE
Marked library link is broken or not redirecting to the proper page

### ISSUE THREAD

**Issue by LukyVj** [PolymerElements/marked-element#13]
Hi, I don't think this is the proper marked page :  
![](http://puu.sh/kelAe/11b0961ac0.png)

**Comment by samccone** [comment]
Ha Yep !

**Comment by samccone** [comment]
@LukyVj I think this was fixed a while ago:
https://github.com/PolymerElements/marked-element/pull/6/files

Where did you find this link?

**Comment by notwaldorf** [comment]
Closing, looks fixed
