### ISSUE TITLE
Loading markdown from server and caching. Question.

### ISSUE THREAD

**Issue by ghost** [PolymerElements/marked-element#14]
I noticed that this component allows the markup to be referenced from a script tag, so I can have the content stored in Google storage in a bucket, and so it acts as a poor man's cms.

Is my understanding correct ?

**Comment by ebidel** [comment]
You could certainly load the content from a sever. However, the element doesn't support `<script src>`. You'd have to inject the text directly on the page. However, you could also use it with iron-ajax, like this example: https://github.com/Polymer/marked-element/issues/12
