### ISSUE TITLE
[Feature request] Accept options in attribute

### ISSUE THREAD

**Issue by Holi0317** [PolymerElements/marked-element#17]
Make this element to take an object of options and pass it to marked library. This can avoid setting option globally.

**Comment by sebs** [comment]
I am working on this and have some questions on how to handle the boolean parameters. Is there a best practice how to pass a boolean false to an element attribute?

**Comment by kevinpschaaf** [comment]
Resolved in https://github.com/PolymerElements/marked-element/pull/19.
