### ISSUE TITLE
vulcanize removes whitespace

### ISSUE THREAD

**Issue by sebs** [PolymerElements/marked-element#18]
when you trigger a vulcanize on a field with markdown, all whitespace gets removed and minified. This modifies the markdown source before the toHtml process.

**Comment by ebidel** [comment]
You probably want to use the `.text` property in cases like this. I thought Vulcanize didn't strip whitespace though...?

**Comment by stramel** [comment]
@ebidel @notwaldorf @e111077 @FredKSchott I think this can be closed... I haven't seen anything like this with the latest build process and I believe vulcanize has been deprecated?

**Comment by e111077** [comment]
What is the story on supporting vulcanize, @FredKSchott @rictic?

**Comment by sebs** [comment]
ah ok, yeah close it if ya like. Everything has changed since I opened this one. There is no vulcanize anymore I guess.
