### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by soonick** [PolymerElements/marked-element#24]
Hello,

Is syntax highlighting supported? In the demo you have a piece of code using:

``````
```html 
``````

But it not colored.

![rendered](https://cloud.githubusercontent.com/assets/281836/11710461/b147dae0-9f1f-11e5-8b97-69c85fe808a4.png)

**Comment by notwaldorf** [comment]
`marked-element` doesn't do any syntax highlighting, but `prism-highlighter` does, and it's super easy to use! Here's an example of the two working together: http://jsbin.com/yegodu/edit?html,output

You basically just have to add a `<prism-highlighter></prism-highlighter>` element on your page (or wherever you're using `marked-element`) and you get highlighting!

**Comment by soonick** [comment]
Thanks. That is exactly what I needed :)
