### ISSUE TITLE
Does marked element do syntax highlighting for code?

### ISSUE THREAD

**Issue by chriswalz** [PolymerElements/marked-element#28]
I was expecting this to text to have syntax highlighting in a marked element. If it's supposed to be this way, will syntax highlighting be a feature in an upcoming version? 

``````
```html
<awesome-sauce>
    <div>Oops, I'm about to forget to close this div.
</awesome-sauce>
```
``````

<img width="664" alt="screen shot 2016-01-19 at 12 02 32 am" src="https://cloud.githubusercontent.com/assets/6971318/12410163/0577c348-be40-11e5-9db7-802bb171b31f.png">

**Comment by notwaldorf** [comment]
`marked-element` doesn't do any syntax highlighting, but `prism-highlighter` does, and it's super easy to use! Here's an example of the two working together: http://jsbin.com/yegodu/edit?html,output

You basically just have to add a `<prism-highlighter></prism-highlighter>` element on your page (or wherever you're using `marked-element`) and you get highlighting!

**Comment by chriswalz** [comment]
Thanks!
