### ISSUE TITLE
textarea newline not showing in markdown

### ISSUE THREAD

**Issue by thexs-dev** [PolymerElements/marked-element#30]
I have this simple combination:

```
   <paper-textarea value="{{content}}"></paper-textarea>
   <marked-element markdown="{{content}}">
```

However, a newline in textarea won't show up in marked-element as I expected, unless it's followed by a space or there are two newlines
Is that an issue in either element or the expected behavior?
Thanks, Fausto
p.s. MD from this GitHub comments page works as I'd expected

**Comment by NicolasRannou** [comment]
+1...

**Comment by thexs-dev** [comment]
To allow for GFM line breaks, so there's no need to use MD's two-space line breaks, I just included the following line of code within a script tag

`window.marked.options({breaks:true}); // to enable GFM single line break
`
