### ISSUE TITLE
Easier addition of new programming languages 

### ISSUE THREAD

**Issue by kishaningithub** [PolymerElements/marked-element#32]
### Description

   Must be easier to add new languages instead of forking, updating gulp file of prism and
creating a new custom component.
Suggestion: Make it a part of your yeoman "generator-polymer". B-)
### Expected outcome

Must add a new language to this element without breaking a sweat.
### Actual outcome

Adding does break a sweat.

### Steps to reproduce

1) Try adding a new language to this element without breaking a sweat.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by TimvdLippe** [comment]
I think this issue has been resolved in `prism-element` with https://github.com/PolymerElements/prism-element/pull/12

**Comment by stramel** [comment]
@FredKSchott I believe @TimvdLippe is correct that this should be handled through prism-element?
