### ISSUE TITLE
Add optional toolbar for bold, italics, quotes, code, link, bullets, numbering, task list.

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/marked-element#35]
### Description

It would make it easier for users to use the component if there were a toolbar with buttons for common markdown annotations like: bold, italics, quote, code snippet, links, bullet points, numbered items and task lists (just as you see in this editor whenever you file a bug).

**Comment by stramel** [comment]
This sounds more like a Markdown Input/Editor/WYSIWYG rather than this which is for displaying Markdown content. 

I could see this being useful as a separate element. Maybe implementing this for a preview section?

**Comment by stramel** [comment]
Warning: Shameless plug, I threw together a markdown editor. Hopefully, y'all will give it a shot and give me some feedback.

https://github.com/MaritzSTL/mtz-marked-editor works with `textarea` and will work with `paper-textarea` with my fork that is currently in review (https://github.com/PolymerElements/paper-input/pull/557).

I think that this is outside the scope of this element but can be paired with the editor to do a preview or render the output.

@e111077 You good with closing this one out?

**Comment by e111077** [comment]
Yeah, @stramel is right, I think this is out of the scope of this element.
