### ISSUE TITLE
Line break support

### ISSUE THREAD

**Issue by Boscop** [PolymerElements/marked-element#42]
Is there a way to have newlines for every newline in the markdown?
The marked library supports the `breaks` and `gfm` options.
But why aren't they exposed in `marked-element`?
Please add them!

In my usecase I want a html line break (`<br>`) wherever the string has a newline (`\n`)

**Comment by FredKSchott** [comment]
+1, we should definitely support the options that marked supports.

**Comment by stevehansen** [comment]
I've changed this with `marked.default.break = true;` because I always needed it

**Comment by Boscop** [comment]
@stevehansen How do you mean that? I don't see a default property on this element.

**Comment by stevehansen** [comment]
The marked variable is the underlying library that is used. So using that snippet in javascript will enable soft breaks for all marked-elements on the current page.

```html
<body>
<script>marked.default.break = true;</script>
<marked-element></marked-element>
</body>
```

**Comment by Boscop** [comment]
@stevehansen `marked` should be a global variable, right? But if I try this in my custom element where I have the marked-element as a child, it doesn't work:
```js
ready: function() {
  marked.default.break = true;
}
```
> Uncaught TypeError: Cannot set property 'break' of undefined
    at HTMLElement.ready

**Comment by stevehansen** [comment]
My bad, was writing the code out of my head, it should have been defaults instead of just default

**Comment by Boscop** [comment]
Ah, I had to also write `breaks` instead of `break`:
```js
marked.defaults.breaks = true;
```
Now it works, thanks!
But nevertheless, this should be exposed via an attribute..
(Also `sanitize` and `gfm`.)
