### ISSUE TITLE
marked-element doesn't have no more the scrollbar

### ISSUE THREAD

**Issue by Abe90** [PolymerElements/marked-element#45]
The `marked-element` element doesn't have no more the scrollbar and overflowing from parent.
The issue was introduced here https://github.com/PolymerElements/marked-element/pull/38

Demo: https://www.webcomponents.org/element/Abe90/paper-avatar/demo/demo/index.html

**Comment by notwaldorf** [comment]
Oooof, you're right. I don't want to revert that change since a bunch of time has passed since it's landed. Would you mind sending a PR that adds back `display:block`?
/cc @FredKSchott
