### ISSUE TITLE
Support for  target="_blank" for links

### ISSUE THREAD

**Issue by Boscop** [PolymerElements/marked-element#47]
It would be useful to have an option to open all links in the markdown in a new tab with ` target="_blank"`.

**Comment by FredKSchott** [comment]
This is now possible via https://github.com/PolymerElements/marked-element/issues/4.

Since we've heard this request in a few issues now, we may want to make a shortcut for this configuration.

**Comment by Boscop** [comment]
@FredKSchott How could this be done with that feature?
I don't see a way to pass the renderer to the element.

**Comment by FredKSchott** [comment]
The property is `renderer`, there's info in #44 & [here](https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L115) about how to use it:
