### ISSUE TITLE
Changes in v1.4.0 contain ES2015 method shorthand syntax, causing issues in older browsers

### ISSUE THREAD

**Issue by jimivdw** [PolymerElements/marked-element#53]
### Description
ES2015 shorthands are used to define the `_handleError` method: https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L327. Therefore, the component will no longer work in browsers that do not support this, including IE11.

### Expected outcome
No ES2015+ syntax is used, component works in all browsers supported by Polymer (https://www.polymer-project.org/1.0/docs/browsers)

### Actual outcome
ES2015 syntax is used, causing issues in (at least) IE11.

### Live Demo
Not really a demo, but https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L327.

### Steps to reproduce
n/a

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [x] IE 10

**Comment by Maksim-Bartoshyk** [comment]
uglifyjs also unable to parse such code

**Comment by stramel** [comment]
Shoot! Sorry guys! I will have a fix in shortly!
