### ISSUE TITLE
Unable to bind script tag's src attribute

### ISSUE THREAD

**Issue by vpusher** [PolymerElements/marked-element#57]
### Description

When using `<marked-element>` in a **template** and binding the `src` attribute of the `<script>` tag, the `src`attribute is always found empty in the  `<marked-element>` ready callback. The attribute seems to be read a bit early.

### Expected outcome

The `<marked-element>` should be able to read the `src` attribute properly and make the request, so the markdown file could be downloaded and displayed.

### Actual outcome

Actually the `src` attribute is not bound (or bound too late), and no markdown is displayed.

### Live Demo

https://jsbin.com/gaqoqoxuji/1/edit?html,output

### Steps to reproduce

See live demo snippet.

### Browsers Affected

All

### Proposal

What about read the `src` attribute in the attached callback instead ?

**Comment by FredKSchott** [comment]
@e111077 what do you think about @stramel's idea here? Makes sense to me but I'd love to get get a more experienced opinion.

**Comment by e111077** [comment]
~Looks like we need to call the `request` function on `src`'s observer~

err took another look

**Comment by vpusher** [comment]
@e111077 @FredKSchott Thanks guys. It was very quick! I appreciate it. 👍
