### ISSUE TITLE
binding script src might only work once

### ISSUE THREAD

**Issue by robrez** [PolymerElements/marked-element#62]
### Description
When attempting to re-use a `marked-element` instance to render different MD files by binding to the script's `src` attribute, there are scenarios that fail.

### Expected outcome
Markdown changes when property bound to `src` changes

### Actual outcome
Markdown does not change when property bound to `src` changes

### Steps to reproduce
The setup is similar to the example from the docs; Except the `source` property does not start out as undefined... eg:
```html
<marked-element>
  <div class="markdown-html"></div>
  <script type="text/markdown" src$="[[source]]"></script>
</marked-element>
...
<script>
  static get properties() {
    source: {
      type: String, value: "README.md"
    }
  }
</script>
```

Subsequent changes to the source property will have no effect.

In my particular case, the value of source comes in from a parent element as a result from routing. Since the source property has a value, by the time marked-element's ready function executes, [this](https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L205) `if` statement is true... preventing the mutation observer in the `else` from being bound.

My workaround was to actually bind a dummy property whose value was assigned from an observer on the real source property.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by FredKSchott** [comment]
Can reproduce.

As far as I know we've never supported this behavior, but +1 for adding support. Filing as an enhancement.

I Won't be able to get to this anytime soon, but would be happy to review a PR.

**Comment by stramel** [comment]
@FredKSchott I believe this is a bug. I will try to put out a fix for it.
