### ISSUE TITLE
marked node_module missing + wrong reference

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/marked-element#76]
With 3.0, I'd expect the marked-element to download marked into the node_modules root folder. right now it's not installed. On top of that, the path reference needs to point to the marked folder in the root.

**Comment by stramel** [comment]
Yeah it does look like it has some things wrong with it. I will work on fixing these and bring them up in the auto-modulizer tooling.

**Comment by stramel** [comment]
This is covered under these upstream issues:

https://github.com/Polymer/polymer-modulizer/issues/174
https://github.com/Polymer/polymer-modulizer/issues/133
