### ISSUE TITLE
Replace marked library with 8fold-marked

### ISSUE THREAD

**Issue by ankon** [PolymerElements/marked-element#82]
### Description

The https://github.com/chjj/marked project seems to be unmaintained right now, and instead there is https://github.com/8fold/marked. This contains at least one additional XSS fix, which this element should pick up.

### Expected outcome

8fold-marked is used.

### Actual outcome

marked is used.

**Comment by ankon** [comment]
XSS fix: https://github.com/chjj/marked/pull/844, applied at https://github.com/8fold/marked/commit/8f9d0b72f5606ed32057049f387161dd41c36ade

Note also https://github.com/PolymerElements/marked-element/issues/40 exists since a while, asking for better defaults.

**Comment by stramel** [comment]
marked library was updated to cover the XSS issues and tagged as 0.3.9

**Comment by ankon** [comment]
@stramel thanks.

For being horribly paranoid: could this project explicitly bump the library requirement to 0.3.9?

**Comment by stramel** [comment]
@ankon I put out #84  for review, we'll see what they think.
