### ISSUE TITLE
Webpack support broken

### ISSUE THREAD

**Issue by jpradelle** [PolymerElements/marked-element#96]
Issue with webpack using @polymer/iron-demo-helpers/demo-snippet on version 3.0.0-pre.23:
```
Uncaught ReferenceError: marked is not defined
    at HTMLElement.render (marked-element.js:298)
```

I think this has been fixed in https://github.com/PolymerElements/marked-element/issues/81 and then broke again.

`&& window.require` has been added here https://github.com/PolymerElements/marked-element/commit/1fef15da17555cb91f1b18fed1aa7666ba3ebda9#diff-b3e973a07f826cf78314752a8b5a4cfcR13
If I revert that line to `if (!window.marked) {`, it fixes the bug, but I don't understand why `&& window.require` has been added.

**Comment by 43081j** [comment]
Yup I'm seeing this problem too.

Webpack doesn't introduce a `window.require`, it replaces `require` calls with a `__webpack_require__` on build.

So we should probably `if (!window.marked && require) {`

cc @e111077

**Comment by e111077** [comment]
It was added for Polymer 3 support in which modules run in strict mode and this will cause an exception otherwise. I suppose the change can be reverted for 2.x to support we pack, but this is a no-go for us modules.

We are currently in a code freeze so this reversion may have to wait

**Comment by e111077** [comment]
misread. this is in the 3.x branch. Did some local testing. It seems to work just fine without the check. Will make a PR to revert

**Comment by jpradelle** [comment]
I confirm it's fixed, thanks
